/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mcomputing.supermarketsystem;

import com.mcomputing.entity.Shift;
import com.mcomputing.entity.User;
import com.mcomputing.services.ProductRequest;
import com.mcomputing.services.ShiftRequest;
import com.mcomputing.services.UserRequest;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Shifts extends javax.swing.JFrame {

    User user;
    ShiftRequest request;
    UserRequest userRequest;
    DefaultTableModel defaultTableModel;
    String accessRights = "Only manager or admin can add, edit or delete shifts";

    public Shifts() {
        setup();
    }

    public Shifts(User user) {
       setup();
        this.user = user;
    }
    
    public void setup(){
         initComponents();
        SelectUser();
        SelectShift();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IdTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DateTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        StaffIdTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShiftsTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        ClearBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        StaffTable = new javax.swing.JTable();
        SignUpLink = new javax.swing.JLabel();
        ProductsLink = new javax.swing.JLabel();
        InventoryLink1 = new javax.swing.JLabel();
        DeliveryLink = new javax.swing.JLabel();
        RegisterLink = new javax.swing.JLabel();
        LoginLink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 200, 10));

        CloseBtn.setBackground(new java.awt.Color(204, 204, 255));
        CloseBtn.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(51, 0, 51));
        CloseBtn.setText(" x");
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Staff Shifting");

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Shift Id");

        IdTf.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        IdTf.setForeground(new java.awt.Color(51, 0, 51));

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Date");

        DateTf.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        DateTf.setForeground(new java.awt.Color(51, 0, 51));
        DateTf.setText("yyyy-mm-dd");

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Shift Staff Id");

        StaffIdTf.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        StaffIdTf.setForeground(new java.awt.Color(51, 0, 51));

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Available Staff");

        AddBtn.setBackground(new java.awt.Color(250, 200, 10));
        AddBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(51, 0, 51));
        AddBtn.setText("Add Shift");
        AddBtn.setBorderPainted(false);
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(250, 200, 10));
        DeleteBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(51, 0, 51));
        DeleteBtn.setText("Delete Shift");
        DeleteBtn.setBorderPainted(false);
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });

        EditBtn.setBackground(new java.awt.Color(250, 200, 10));
        EditBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        EditBtn.setForeground(new java.awt.Color(51, 0, 51));
        EditBtn.setText("Update Shift");
        EditBtn.setBorderPainted(false);
        EditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBtnMouseClicked(evt);
            }
        });
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        ShiftsTable.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        ShiftsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shift Id", "Date", "Staff Id"
            }
        ));
        ShiftsTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ShiftsTable.setSelectionBackground(new java.awt.Color(255, 200, 10));
        ShiftsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShiftsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ShiftsTable);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Shifts");

        ClearBtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(51, 0, 51));
        ClearBtn.setText("Clear");
        ClearBtn.setBorderPainted(false);
        ClearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearBtnMouseClicked(evt);
            }
        });

        StaffTable.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        StaffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff Id", "Name", "Is Manager"
            }
        ));
        StaffTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        StaffTable.setSelectionBackground(new java.awt.Color(255, 200, 10));
        StaffTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StaffTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(395, 395, 395)
                .addComponent(jLabel10)
                .addGap(721, 721, 721))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StaffIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        SignUpLink.setBackground(new java.awt.Color(204, 204, 255));
        SignUpLink.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        SignUpLink.setForeground(new java.awt.Color(51, 0, 51));
        SignUpLink.setText("Super Market App");

        ProductsLink.setBackground(new java.awt.Color(204, 204, 255));
        ProductsLink.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        ProductsLink.setForeground(new java.awt.Color(51, 0, 51));
        ProductsLink.setText("PRODUCTS");
        ProductsLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsLinkMouseClicked(evt);
            }
        });

        InventoryLink1.setBackground(new java.awt.Color(204, 204, 255));
        InventoryLink1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        InventoryLink1.setForeground(new java.awt.Color(51, 0, 51));
        InventoryLink1.setText("INVENTORY");
        InventoryLink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryLink1MouseClicked(evt);
            }
        });

        DeliveryLink.setBackground(new java.awt.Color(204, 204, 255));
        DeliveryLink.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        DeliveryLink.setForeground(new java.awt.Color(51, 0, 51));
        DeliveryLink.setText("DELIVERY");
        DeliveryLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeliveryLinkMouseClicked(evt);
            }
        });

        RegisterLink.setBackground(new java.awt.Color(204, 204, 255));
        RegisterLink.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        RegisterLink.setForeground(new java.awt.Color(51, 0, 51));
        RegisterLink.setText("Create New User");
        RegisterLink.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        RegisterLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLinkMouseClicked(evt);
            }
        });

        LoginLink.setBackground(new java.awt.Color(204, 204, 255));
        LoginLink.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        LoginLink.setForeground(new java.awt.Color(51, 0, 51));
        LoginLink.setText("Log out");
        LoginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignUpLink, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginLink)
                    .addComponent(InventoryLink1)
                    .addComponent(RegisterLink)
                    .addComponent(DeliveryLink)
                    .addComponent(ProductsLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(SignUpLink)
                .addGap(59, 59, 59)
                .addComponent(ProductsLink)
                .addGap(38, 38, 38)
                .addComponent(InventoryLink1)
                .addGap(35, 35, 35)
                .addComponent(DeliveryLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginLink)
                .addGap(230, 230, 230))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CloseBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void SelectShift() {
        try {

            request = new ShiftRequest();
            List<Shift> shifts = new ArrayList();
            shifts = request.sendFindAllShiftsRequest();

            addRowToShiftJtable(shifts);

        } catch (IOException ex) {
            Logger.getLogger(Shifts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        public void SelectUser() {
        try {

            userRequest = new UserRequest();
            List<User> users = new ArrayList();
            users = userRequest.sendFindAllUsersRequest();

            addRowToStaffJtable(users);

        } catch (IOException ex) {
            Logger.getLogger(Shifts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addRowToShiftJtable(List<Shift> ls) {
         defaultTableModel = (DefaultTableModel) ShiftsTable.getModel();

        if (defaultTableModel.getRowCount() > 0) {
            for (int i = defaultTableModel.getRowCount() - 1; i > -1; i--) {
                defaultTableModel.removeRow(i);
            }
        }
        Object[] rowData = new Object[5];
        for (int i = 0; i < ls.size(); i++) {
            rowData[0] = ls.get(i).getShiftId();
            rowData[1] = ls.get(i).getShiftDate();
            rowData[2] = ls.get(i).getShiftUserId();
            defaultTableModel.addRow(rowData);

        }
    }
    
      public void addRowToStaffJtable(List<User> ls) {
         defaultTableModel = (DefaultTableModel) StaffTable.getModel();

        if (defaultTableModel.getRowCount() > 0) {
            for (int i = defaultTableModel.getRowCount() - 1; i > -1; i--) {
                defaultTableModel.removeRow(i);
            }
        }
        Object[] rowData = new Object[5];
        for (int i = 0; i < ls.size(); i++) {
            rowData[0] = ls.get(i).getUserId();
            rowData[1] = ls.get(i).getUserName();
            rowData[2] = ls.get(i).isUserManager();
            defaultTableModel.addRow(rowData);

        }
    }

       
    
    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_CloseBtnMouseClicked

    
    private void StaffTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffTableMouseClicked
        defaultTableModel = (DefaultTableModel) StaffTable.getModel();
        int myIndex = StaffTable.getSelectedRow();
        StaffIdTf.setText(defaultTableModel.getValueAt(myIndex, 0).toString());
 
    }//GEN-LAST:event_StaffTableMouseClicked

    private void ClearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBtnMouseClicked
        IdTf.setText("");
        DateTf.setText("");
        StaffIdTf.setText("");
    }//GEN-LAST:event_ClearBtnMouseClicked

    private void ShiftsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShiftsTableMouseClicked
        defaultTableModel = (DefaultTableModel) ShiftsTable.getModel();
        int myIndex = ShiftsTable.getSelectedRow();
        IdTf.setText(defaultTableModel.getValueAt(myIndex, 0).toString());
        DateTf.setText(defaultTableModel.getValueAt(myIndex, 1).toString());
        StaffIdTf.setText(defaultTableModel.getValueAt(myIndex, 2).toString());
 
    }//GEN-LAST:event_ShiftsTableMouseClicked

    private void EditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBtnMouseClicked
        if (user.isUserAdmin() == true || user.isUserManager() == true) {
            if (IdTf.getText().isEmpty() || DateTf.getText().isEmpty()
                || StaffIdTf.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Some information is missing");
            } else {
                try {
                    String jsonInputString = String.format(
                        "{\"shiftId\": %s, \"shiftDate\": \"%s\", \"shiftUserId\":%s}",
                        IdTf.getText(), DateTf.getText(), StaffIdTf.getText());
                    request = new ShiftRequest();
                    System.out.println("sending shift update");
                    String response = request.sendEditShiftRequest(jsonInputString);

                    JOptionPane.showMessageDialog(this, response);
                    SelectShift();
                } catch (IOException ex) {
                    Logger.getLogger(Shifts.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, accessRights);
        }
    }//GEN-LAST:event_EditBtnMouseClicked

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        if (user.isUserAdmin() == true || user.isUserManager() == true) {
            if (IdTf.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter The Product Id To Be Deleted");
            } else {
                try {
                    request = new ShiftRequest();
                    String response = request.sendDeleteShiftRequest(IdTf.getText());
                    JOptionPane.showMessageDialog(this, response);
                    SelectShift();

                } catch (IOException ex) {
                    Logger.getLogger(Shifts.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, accessRights);
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        if (user.isUserAdmin() == true || user.isUserManager() == true) {
            if (DateTf.getText().isEmpty()
                || StaffIdTf.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Some information is missing");
            } else {
                try {
                    String jsonInputString = String.format(
                        "{\"shiftDate\": \"%s\", \"shiftUserId\":%s}",
                        DateTf.getText(), StaffIdTf.getText());
                    request = new ShiftRequest();                   
                    String response = request.sendAddShiftRequest(jsonInputString);

                    JOptionPane.showMessageDialog(this, response);
                    SelectShift();
                } catch (IOException ex) {
                    Logger.getLogger(Shifts.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, accessRights);
        }

    }//GEN-LAST:event_AddBtnMouseClicked

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtnActionPerformed

    private void ProductsLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsLinkMouseClicked
         new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsLinkMouseClicked

    private void InventoryLink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryLink1MouseClicked
        new Inventory(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InventoryLink1MouseClicked

    private void DeliveryLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeliveryLinkMouseClicked
        new Delivery(user).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DeliveryLinkMouseClicked

    private void RegisterLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLinkMouseClicked

        if (!user.isUserAdmin()) {
            JOptionPane.showMessageDialog(this, "This option is available for Admin only");
        } else {
            new Register(user).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_RegisterLinkMouseClicked

    private void LoginLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLinkMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shifts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shifts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JTextField DateTf;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel DeliveryLink;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField IdTf;
    private javax.swing.JLabel InventoryLink1;
    private javax.swing.JLabel LoginLink;
    private javax.swing.JLabel ProductsLink;
    private javax.swing.JLabel RegisterLink;
    private javax.swing.JTable ShiftsTable;
    private javax.swing.JLabel SignUpLink;
    private javax.swing.JTextField StaffIdTf;
    private javax.swing.JTable StaffTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
